version: '3.3'
services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: 'conduit'
      MYSQL_USER: 'conduit'
      MYSQL_PASSWORD: 'conduit'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/user/leone/Documents/mysql
volumes:
  my-db: